
AR=m68k-apple-macos-ar
RANLIB=m68k-apple-macos-ranlib
#AR=powerpc-apple-macos-ar
#RANLIB=powerpc-apple-macos-ranlib


all:
	make -f Makefile.r68 -C src
	make -f Makefile.r68 -C demos
	make -f Makefile.r68 lib

lib:
	rm -f *.a
	cp */*.a .
	
clean:
	make -f Makefile.r68 -C src clean
	make -f Makefile.r68 -C demos clean
	rm -f *.a */*.a
