
#AR=m68k-apple-macos-ar
#RANLIB=m68k-apple-macos-ranlib
AR=powerpc-apple-macos-ar
RANLIB=powerpc-apple-macos-ranlib


all:
	make -f Makefile.r68carb -i -C AGL/Sources/aglDD
	make -f Makefile.r68carb -C AGL/Sources
	make -f Makefile.r68carb -C GL/Sources
	make -f Makefile.r68carb -C GLU/Sources
	make -f Makefile.r68carb -C AUX:TK/Source
	make -f Makefile.r68carb -C Stub\ Libs
	make -f Makefile.r68carb -C GLUT/Source\ Common
	make -f Makefile.r68carb -i -C GLUT/Source\ Mac
	make -f Makefile.r68carb -i -C GLUT_apple
	
lib:
	make -f Makefile.r68carb all
	$(AR) rcv libMesaOpenGLLibraryCarb.a AGL/Sources/*.o AGL/Sources/aglDD/*.o GL/Sources/*.o
	$(RANLIB) libMesaOpenGLLibraryCarb.a
	$(AR) rcv libMesaOpenGLUtilityCarb.a GLU/Sources/*.o
	$(RANLIB) libMesaOpenGLUtilityCarb.a
	$(AR) rcv libglutCarb_pp.a GLUT/Source\ Common/*.o GLUT/Source\ Mac/*.o
	$(RANLIB) libglutCarb_pp.a
	$(AR) rcv libglutCarb.a GLUT_apple/*.o
	$(RANLIB) libglutCarb.a

install:
	make -f Makefile.r68carb lib
	cp *.a $(HOME)/Retro68-build/toolchain/powerpc-apple-macos/lib/.

clean:
	rm -f *.a */*.a
	rm -f */*/*.o */*/*.a
	rm -f */*/*/*.o */*/*/*.a
