LIBNAME=agl

#CC=m68k-apple-macos-gcc
#CXX=m68k-apple-macos-g++
#AR=m68k-apple-macos-ar
#RANLIB=m68k-apple-macos-ranlib
CC=powerpc-apple-macos-gcc
CXX=powerpc-apple-macos-g++
AR=powerpc-apple-macos-ar
RANLIB=powerpc-apple-macos-ranlib

CFLAGS= -I../../../Headers -I../../GL/Sources

OBJS=$(subst .c,.o,$(wildcard *.c))

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<


lib: $(OBJS)
	$(AR) rcv lib$(LIBNAME).a *.o */*.o
	$(RANLIB) lib$(LIBNAME).a

all: $(OBJS)
	make -f Makefile.r68ppc -C aglDD

clean:
	make -f Makefile.r68ppc -C aglDD clean
	rm -f *.o */*.o
