LIBNAME=glut_mac

#CC=m68k-apple-macos-gcc
#CXX=m68k-apple-macos-g++
#AR=m68k-apple-macos-ar
#RANLIB=m68k-apple-macos-ranlib
CC=powerpc-apple-macos-gcc -carbon
CXX=powerpc-apple-macos-g++ -carbon
AR=powerpc-apple-macos-ar
RANLIB=powerpc-apple-macos-ranlib

CFLAGS= -I../../../Headers -I../Source\ Mac -I$(HOME)/PowerPlant/Commander\ Classes -I$(HOME)/PowerPlant/Feature\ Classes -I$(HOME)/PowerPlant/PowerPlant\ Headers -I$(HOME)/PowerPlant/Utility\ Classes -I$(HOME)/PowerPlant/Array\ Classes -I$(HOME)/PowerPlant/AppleEvent\ Classes -I$(HOME)/PowerPlant/Support\ Classes -I$(HOME)/PowerPlant/Pane\ Classes

OBJS=$(subst .c,.o,$(wildcard *.c)) $(subst .cp,.o,$(wildcard *.cp))

.SUFFIXES: .cp

.c.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

.cp.o:
	$(CXX) $(CFLAGS) -c -o $@ $<


lib: $(OBJS)
	$(AR) rcv lib$(LIBNAME).a $(OBJS)
	$(RANLIB) lib$(LIBNAME).a

all: $(OBJS)

clean:
	rm -f *.o *.a
