
all:
	make -f Makefile.r68ppc -i -C Chess
	make -f Makefile.r68ppc -i -C Glutmech
	make -f Makefile.r68ppc -i -C Geoface
	make -f Makefile.r68ppc -i -C Ideas
	make -f Makefile.r68ppc -i -C OpenGL\ logo
	make -f Makefile.r68ppc -i -C Rollercoaster
	make -f Makefile.r68ppc -i -C UnderWater
	make -f Makefile.r68ppc -i -C Walker
	make -f Makefile.r68ppc -i -C Sample
	
clean:
	make -f Makefile.r68ppc -i -C Chess clean
	make -f Makefile.r68ppc -i -C Glutmech clean
	make -f Makefile.r68ppc -i -C Geoface clean
	make -f Makefile.r68ppc -i -C Ideas clean
	make -f Makefile.r68ppc -i -C OpenGL\ logo clean
	make -f Makefile.r68ppc -i -C Rollercoaster clean
	make -f Makefile.r68ppc -i -C UnderWater clean
	make -f Makefile.r68ppc -i -C Walker clean
	make -f Makefile.r68ppc -i -C Sample clean
	rm -rf */*.o
	rm -rf */*\ Data
